version: 'newest'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:

      # Could not see nginx start page (got 403 Forbidden) until I modified the line below to point to the following location.
      # Warning the random charachters below is hard-coded and IT DOES change.

      # /var/www/html:/var/lib/docker/overlay2/9c71801cbeba2fa3dabe83ecdc3ae95caa094444fb05d9d818983dee5cd0f4ba/merged/usr/share/nginx/html
      #- /nginx.conf:/var/lib/docker/overlay2/9c71801cbeba2fa3dabe83ecdc3ae95caa094444fb05d9d818983dee5cd0f4ba/merged/etc/nginx/conf.d/default.conf

      # The following line will break the nginx returning the homepage.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # - /workspaces/Assignment1/nginx.conf:/etc/nginx/conf.d/default.conf

    restart: always

  # Can't run docker-compose as "sudo", this will cause the following image fetch to fail.
  front-end:
    image: "ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main"
    volumes:
      - /adapter:/source/adapter
    ports:
      - "80"
    restart: always

  server:
    image: "node:20"
    volumes:
      - ./:/app
    working_dir: /app
    command: "npx -y tsx ./index.ts"

  server-two:
    image: "node:20"
    volumes:
      - ./:/app
    working_dir: /app
    command: "npx -y tsx ./index.ts"

  server-three:
    image: "node:20"
    volumes:
      - ./:/app
    working_dir: /app
    command: "npx -y tsx ./index.ts"

  # MUST add mongo here. Mongo from inside .devcontainer was causing our "server" to fail.
  # Once we added mongo inside this docker.compose.yaml and not the one inside .devcontainer, works as expected now.
  mongo:
    image: mongo:latest
