version: 'newest'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # Could not see nginx start page (got 403 Forbidden) until I modified the line below to point to the following location.
      - /var/www/html:/var/lib/docker/overlay2/e0b959a91bf71ee1a896b0aa37936cfa2371efa772a909a4f1e503ed211c375f/merged/usr/share/nginx/html
      - ./nginx.conf:/var/lib/docker/overlay2/e11f8eb9d04133b39610d9eb5209ff99147dc2b80851c29654d5c7d5acbafbd6/merged/etc/nginx/conf.d/default.conf
    restart: always

  # Can't run docker-compose as "sudo", this will cause the following image fetch to fail.
  front-end:
    image: "ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main"
    volumes:
      - /adapter:/source/adapter
    ports:
      - "80"
    restart: always
