name: Invoke type checking for TypeScript.
run-name: ${{ github.actor }} is running type checking.
on: [push]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        - run: tsc --noEmit ./src/index.ts